name: Unreal Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epicgames/unreal-engine:dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup environment variables
      run: |
        echo "UE_PATH=/home/ue4/UnrealEngine" >> $GITHUB_ENV

    - name: Build Plugin
      run: |
        # Run the Unreal Automation Tool (UAT) to build the plugin
        "${{ env.UE_PATH }}/Engine/Build/BatchFiles/RunUAT.sh" \
          BuildPlugin \
          -Plugin="${{ github.workspace }}/sdks/ue4/Quilkin.uplugin" \ # Path to the plugin
          -Package="${{ github.workspace }}/PluginBuild" \ # Output directory for the built plugin
          -Rocket

    - name: Run Tests
      run: |
        # Run the tests using UE4Editor-Cmd (Command Line) with the Automation framework
        "${{ env.UE_PATH }}/Engine/Binaries/Linux/UE4Editor-Cmd" \
          -run=Automation \ # Run the Automation framework for testing
          -Plugin="${{ github.workspace }}/sdks/ue4/Quilkin.uplugin" \ # Path to the plugin
          -unattended \ # Run in unattended mode (no user interaction)
          -nopause \ # Do not pause after executing the command
          -testexit="Automation Test Queue Empty" \ # Exit when the test queue is empty
          -log # Output log information
